/**
 * Shared companion / kid portrait + ornament kit.
 * OWNER: frontend agent.
 *
 * Everything the pre-run screens draw that is *art* rather than *layout* lives here:
 * companion portrait plates (with pointer parallax + spectral shimmer), procedurally
 * generated Kid portraits, the MIDNIGHT MENAGERIE logo cartouche, and the filigree /
 * cobweb / candle / bat ornaments that give the mansion its character.
 *
 * No hex literals: every colour is a token from ui/tokens.css, or derived from one
 * with color-mix() in the owning stylesheet. SVG here inherits `currentColor` or uses
 * CSS custom properties so the stylesheet stays in charge.
 */

import { COMPANIONS, KIDS } from '../data/schema.js';
import { Save } from '../core/save.js';
import { petImg, petPhoto, warmFaces, petKey } from './petart.js';

// The pet photographs are generated in ui/petart.js. Re-exported here so scenes
// keep importing all their art from one place. The Kids are NOT generated —
// they are authored paintings, loaded by `kidImg` further down this file.
export { petImg, petPhoto, warmFaces, petKey };

// ── stylesheet loading ──────────────────────────────────────────────────────
// index.html is owned by the lead and only links tokens.css + base.css, so scene
// stylesheets attach themselves on first use. Idempotent, and resolves once loaded
// so a scene can await it and never render a single unstyled frame.
const _css = new Map();
export function ensureCss(href) {
  const url = String(href);
  if (_css.has(url)) return _css.get(url);
  const p = new Promise((resolve) => {
    const existing = document.querySelector(`link[data-mmcss="${CSS.escape(url)}"]`);
    if (existing) return resolve();
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = url;
    link.dataset.mmcss = url;
    link.addEventListener('load', () => resolve(), { once: true });
    link.addEventListener('error', () => resolve(), { once: true });
    document.head.appendChild(link);
    // never let a missing stylesheet stall a scene
    setTimeout(resolve, 1200);
  });
  _css.set(url, p);
  return p;
}

/** Wait for the display webfonts so SVG/text measurement is stable. Never rejects. */
export function fontsReady(timeout = 1500) {
  return Promise.race([
    (document.fonts?.ready ?? Promise.resolve()).catch(() => {}),
    new Promise((r) => setTimeout(r, timeout)),
  ]);
}

// ── asset paths ─────────────────────────────────────────────────────────────
const ASSETS = new URL('../../assets/', import.meta.url).href;
export const PORTRAIT_W = 828;
export const PORTRAIT_H = 516;
export const PORTRAIT_ASPECT = PORTRAIT_W / PORTRAIT_H;

/** Companions that have a dedicated 768px hero render. */
export const HERO_ART = new Set(['bones', 'pipkin', 'taffy']);

/** Downscaled grid thumbnail. `variant`: '@1x' | '@2x' | '-card'. */
export function thumbSrc(slug, variant = '@2x') {
  return `${ASSETS}portraits/thumbs/${slug}${variant}.png`;
}
export function fullSrc(slug) { return `${ASSETS}portraits/${slug}.png`; }

// ── the Menagerie board ─────────────────────────────────────────────────────
/**
 * `UI/selectCompanion.png` IS the Companion Select screen — the wordmark in its
 * cartouche, the candles, the cobwebs and sixteen framed portraits, one
 * painting. Two prepared copies of it live in `assets/ui/`:
 *
 *   'board'  the sheet, verbatim.
 *   'empty'  the same painting with all sixteen frames emptied to a dark
 *            recess — same frames, same gold, nothing inside them.
 *
 * The screen draws `empty` as its base and lays a sprite of `board` over the
 * cells whose Companion is available. An un-freed Companion therefore has no
 * element, no alt text and no pixels anywhere on the page: hidden, not dimmed.
 *
 * Regenerate both with `python tools/prep_board.py`.
 */
export function boardSrc(which = 'board') { return `${ASSETS}ui/menagerie-${which}.png`; }

/**
 * Where each Companion's frame sits on the board, as [x, y, w, h] fractions.
 *
 * MEASURED, not derived: the painted frames are not on a regular pitch — row 0
 * is 257px tall, row 2 is 235px, and the four columns differ by up to 7px. A
 * uniform grid drawn over this sheet misses by half a frame at the corners.
 * Each rect is the gold frame plus 4px of the black gutter on every side, so a
 * hovered frame can lift and scale without ever showing a cut edge.
 *
 * Generated by `python tools/prep_board.py` — paste its output over this block.
 */
/* generated by tools/prep_board.py */
export const BOARD_CELLS = {
  marmalade: [0.00957, 0.14593, 0.24163, 0.21132],
  wisp: [0.25279, 0.14593, 0.24721, 0.21132],
  crumbula: [0.50080, 0.14593, 0.24561, 0.21132],
  boggle: [0.74721, 0.14593, 0.24163, 0.21132],
  bones: [0.00957, 0.35726, 0.24163, 0.20175],
  pipkin: [0.25279, 0.35726, 0.24721, 0.20175],
  taffy: [0.50080, 0.35726, 0.24561, 0.20175],
  truffle: [0.74721, 0.35726, 0.24163, 0.20175],
  hush: [0.00957, 0.55901, 0.24163, 0.19378],
  mopsy: [0.25279, 0.55901, 0.24721, 0.19378],
  drizzle: [0.50080, 0.55901, 0.24561, 0.19378],
  pudding: [0.74721, 0.55901, 0.24163, 0.19378],
  wink: [0.00957, 0.75279, 0.24163, 0.20893],
  crinkle: [0.25279, 0.75279, 0.24721, 0.20893],
  mossbit: [0.50080, 0.75279, 0.24561, 0.20893],
  brambleboo: [0.74721, 0.75279, 0.24163, 0.20893],
};

/**
 * The custom properties one board cell needs, as a `style` string.
 *
 * `--px`/`--py` are the background-position percentages that put cell (x,y) of
 * the whole board inside an element that is only (w,h) of it. CSS positions a
 * background by aligning p% of the image with p% of the box, so the offset is
 * `(box - image) * p`; solving `(w-1)·B·p = -x·B` gives `p = x / (1 - w)`.
 * Doing that arithmetic here rather than in the stylesheet keeps the CSS to one
 * rule for all sixteen.
 */
export function boardCellVars(slug) {
  const cell = BOARD_CELLS[slug];
  if (!cell) return '';
  const [x, y, w, h] = cell;
  return `--cx:${x};--cy:${y};--cw:${w};--ch:${h};` +
    `--px:${(x / (1 - w) * 100).toFixed(4)}%;--py:${(y / (1 - h) * 100).toFixed(4)}%`;
}
export function heroSrc(slug) {
  return HERO_ART.has(slug) ? `${ASSETS}hero/${slug}.jpg` : thumbSrc(slug, '-card');
}
export function blueprintSrc(name = 'mansion') { return `${ASSETS}blueprint/${name}.png`; }

// ── the Title screen ────────────────────────────────────────────────────────
/**
 * The Title screen is two authored paintings, prepared by
 * `python tools/prep_menu_art.py` and committed (no build step, CONTRACTS #1):
 *
 *   'menu'   `UI/mainMenu.png` — the mansion exterior at night, 1672x941, ~16:9.
 *            The whole screen. Cover-fit; the front door and the cobbled path
 *            are the composition's centre of gravity, so the crop anchors low.
 *   'title'  `UI/title.png` — the MIDNIGHT MENAGERIE wordmark. Its black field
 *            is keyed to alpha on LUMINANCE (not a chroma key, which would eat
 *            the cartouche interior and the shadow inside the letter bevels)
 *            and trimmed to its own ink, 2102x688. The plate interior stays at
 *            partial alpha on purpose: the house shows through it, so it reads
 *            as a lit sign hung over the gate rather than a sticker.
 *
 * `select-kid.jpg` is prepared from `UI/selectKid.png` by the same script and
 * is NOT wired to anything yet — the designer has not asked for it.
 */
export function menuArtSrc(which = 'menu') {
  return which === 'title' ? `${ASSETS}ui/title.png` : `${ASSETS}ui/main-menu.jpg`;
}

export const COMPANION_BY_SLUG = Object.fromEntries(COMPANIONS.map((c) => [c.slug, c]));
export const KID_BY_SLUG = Object.fromEntries(KIDS.map((k) => [k.slug, k]));

// ── who is out of the house ─────────────────────────────────────────────────
/** The four that already live at the clubhouse on a fresh save. */
export const STARTER_COMPANIONS = ['marmalade', 'bones', 'pipkin', 'taffy'];

/**
 * AVAILABLE is not FREED, and treating them as one number put a lie on the
 * counter the whole game is about.
 *
 * There are two questions here and three screens used to answer both with the
 * same set:
 *
 *   available — may I take this Companion in?   starters + lifetime rescues
 *   freed     — did I get this one out of that house?         rescues only
 *
 * An earlier round unified them because the Title said "0 / 16 freed" while
 * Select and the Clubhouse said "4 / 16" on the same save. That was a real bug,
 * but it got unified in the wrong direction: a brand-new save then opened on
 * "4 / 16 MENAGERIE COMPANIONS FREED" with an empty localStorage, claiming four
 * rescues that never happened — and it flattens every real one, because the
 * first Companion you actually free moves the number to five. The four starters
 * were never in the house. They live at the clubhouse; that is why you have
 * them.
 *
 * So `availableCompanions()` decides what is pickable and whose portrait is
 * unlocked, `freedCompanions()` is the score, and a fresh save reads 0 / 16.
 *
 * @param {Iterable<string>} [alsoFreed] slugs freed this session that the save
 *        has not been asked for yet (a just-finished run, mid-expedition).
 * @returns {Set<string>} slugs, deduped.
 */
export function freedCompanions(alsoFreed) {
  const known = new Set(COMPANIONS.map((c) => c.slug));
  const out = new Set();
  for (const slug of [...(Save?.data?.companionsRescued ?? []), ...(alsoFreed ?? [])]) {
    if (known.has(slug)) out.add(slug);
  }
  return out;
}

/** Everyone you may take into the house: the four starters plus everyone freed. */
export function availableCompanions(alsoFreed) {
  const out = freedCompanions(alsoFreed);
  const known = new Set(COMPANIONS.map((c) => c.slug));
  for (const slug of STARTER_COMPANIONS) if (known.has(slug)) out.add(slug);
  return out;
}

/** True for a Companion who is only pickable because they started with you. */
export function isStarter(slug) { return STARTER_COMPANIONS.includes(slug); }

/** How many of the four starters are not (yet) also lifetime rescues. */
export function starterCount(alsoFreed) {
  const freed = freedCompanions(alsoFreed);
  return STARTER_COMPANIONS.filter((s) => !freed.has(s)).length;
}

/** Region slug -> the name the fiction uses. */
export const REGION_NAMES = {
  'foyer': 'the Forgotten Foyer',
  'nursery': 'the Nursery',
  'sleeping-quarters': 'the Sleeping Quarters',
  'kitchens-cellars': 'the Kitchens & Cellars',
  'greenhouse': 'the Greenhouse',
  'graveyard': 'the Graveyard',
  'study-library': 'the Study & Library',
  'attic-observatory': 'the Attic & Observatory',
  'lampworks': 'the Lampworks',
  'ballroom': 'the Ballroom',
  'crypt': 'the Crypt',
  'hedge-maze': 'the Hedge Maze',
  'secret-passages': 'the Secret Passages',
  'bathhouse': 'the Bathhouse',
  'kennels': 'the Kennels',
  'pumpkin-grounds': 'the Pumpkin Grounds',
  'heart': 'the Heart of the House',
};

// ── motion preferences ──────────────────────────────────────────────────────
let _reduceMotion = false;
export function setReduceMotion(v) {
  _reduceMotion = !!v;
  document.documentElement.classList.toggle('mm-reduce-motion', _reduceMotion);
  if (_reduceMotion) parallax.reset();
}
export function reduceMotion() { return _reduceMotion; }

// ── pointer parallax ────────────────────────────────────────────────────────
/**
 * One pointermove listener and one rAF for the whole app, no matter how many
 * portraits are on screen. Each registered element declares a depth; the manager
 * lerps toward the pointer and writes a single composited transform per element.
 * Writes only — never reads layout — so this cannot thrash.
 */
class ParallaxManager {
  constructor() {
    this.items = new Set();
    this.tx = 0; this.ty = 0;   // target, -1..1
    this.cx = 0; this.cy = 0;   // current
    this.raf = 0;
    this._bound = false;
    this._onMove = (e) => {
      this.tx = (e.clientX / Math.max(innerWidth, 1)) * 2 - 1;
      this.ty = (e.clientY / Math.max(innerHeight, 1)) * 2 - 1;
    };
    this._onLeave = () => { this.tx = 0; this.ty = 0; };
  }
  add(el, depth = 1, scale = 1.06) {
    this.items.add({ el, depth, scale });
    this._bind();
    return () => this.remove(el);
  }
  remove(el) {
    for (const it of this.items) if (it.el === el) this.items.delete(it);
    if (!this.items.size) this._unbind();
  }
  reset() {
    this.tx = this.ty = this.cx = this.cy = 0;
    for (const it of this.items) it.el.style.transform = '';
  }
  _bind() {
    if (this._bound) return;
    this._bound = true;
    addEventListener('pointermove', this._onMove, { passive: true });
    addEventListener('pointerleave', this._onLeave, { passive: true });
    const tick = () => {
      this.raf = requestAnimationFrame(tick);
      if (_reduceMotion) return;
      this.cx += (this.tx - this.cx) * 0.075;
      this.cy += (this.ty - this.cy) * 0.075;
      if (Math.abs(this.cx - this.tx) < 0.0008 && Math.abs(this.cy - this.ty) < 0.0008) {
        this.cx = this.tx; this.cy = this.ty;
      }
      for (const it of this.items) {
        const d = it.depth;
        it.el.style.transform =
          `translate3d(${(-this.cx * 9 * d).toFixed(2)}px,${(-this.cy * 6 * d).toFixed(2)}px,0) scale(${it.scale})`;
      }
    };
    this.raf = requestAnimationFrame(tick);
  }
  _unbind() {
    if (!this._bound) return;
    this._bound = false;
    removeEventListener('pointermove', this._onMove);
    removeEventListener('pointerleave', this._onLeave);
    cancelAnimationFrame(this.raf);
  }
}
export const parallax = new ParallaxManager();

// ── small DOM helper ────────────────────────────────────────────────────────
export function el(tag, cls, html) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (html != null) n.innerHTML = html;
  return n;
}
export function svg(markup) {
  const t = document.createElement('template');
  t.innerHTML = markup.trim();
  return t.content.firstElementChild;
}

// ── companion portrait plate ────────────────────────────────────────────────
/**
 * A framed companion portrait. Returns { el, destroy }.
 *  slug     companion slug
 *  variant  thumbnail variant ('@2x' grid, '-card' hero, 'hero' full render)
 *  locked   render as an un-rescued silhouette
 *  parallax depth multiplier; 0 disables
 *  shimmer  add the drifting spectral sheen layer
 */
export function companionPortrait({
  slug, variant = '@2x', locked = false, parallax: depth = 1, shimmer = true, alt,
} = {}) {
  const c = COMPANION_BY_SLUG[slug];
  const wrap = el('div', 'pf' + (locked ? ' is-locked' : ''));
  wrap.dataset.companion = slug;

  const inner = el('div', 'pf__inner');
  const img = document.createElement('img');
  img.className = 'pf__img';
  img.decoding = 'async';
  img.loading = 'eager';
  img.draggable = false;
  if (variant === 'hero') {
    img.src = heroSrc(slug);
    const square = HERO_ART.has(slug);
    img.width = square ? 768 : 560;
    img.height = square ? 768 : Math.round(560 / PORTRAIT_ASPECT);
  } else if (variant === '-card') {
    img.src = thumbSrc(slug, '-card'); img.width = 560; img.height = 349;
  } else if (variant === '@1x') {
    img.src = thumbSrc(slug, '@1x'); img.width = 240; img.height = 150;
  } else {
    img.src = thumbSrc(slug, '@2x'); img.width = 480; img.height = 299;
  }
  img.alt = alt ?? (locked ? `${c?.name ?? slug} — not yet rescued` : `${c?.name ?? slug}, ${c?.title ?? ''}`);
  img.addEventListener('error', () => { img.src = fullSrc(slug); }, { once: true });
  inner.appendChild(img);
  wrap.appendChild(inner);

  if (shimmer && !locked) wrap.appendChild(el('div', 'pf__shimmer'));
  wrap.appendChild(el('div', 'pf__vig'));
  if (locked) {
    wrap.appendChild(svg(`<div class="pf__lock">
      <svg viewBox="0 0 40 46" aria-hidden="true"><path d="M20 2c-6.1 0-11 4.9-11 11v6H6a2 2 0 0 0-2 2v23a2 2 0 0 0 2 2h28a2 2 0 0 0 2-2V21a2 2 0 0 0-2-2h-3v-6c0-6.1-4.9-11-11-11Zm0 5a6 6 0 0 1 6 6v6H14v-6a6 6 0 0 1 6-6Z"/></svg>
    </div>`));
  }

  let off = null;
  if (depth && !_reduceMotion) off = parallax.add(inner, depth, 1.055 + depth * 0.012);
  return {
    el: wrap,
    destroy() { off?.(); off = null; },
  };
}

// ── ornaments ───────────────────────────────────────────────────────────────
// These return SVG *fragments* (a <g>), not standalone <svg> roots: a nested <svg>
// with no width/height defaults to 300x150 and destroys the parent's coordinate
// space. Callers place them with a transform inside their own <svg>.

/**
 * Half of a filigree scroll, drawn as strokes inside a 160x80 box with the
 * attachment point at (0,40). Mirror with scale(-1,1) for the other side.
 */
export const FILIGREE_STEM =
  'M0 45C44 44 62 20 98 18c26-1.5 43 10 40 24-2.5 11.5-17 15-23 6-5-7.5 2-16 10-13 4.5 1.5 5 6 3 8'
  + 'M0 45c40 1 56 23 88 27 24 3 40-4 40-15 0-9-10-13-16-7-5 5-2 12 4 11'
  + 'M2 45C12 44 16 36 13 30';
export const FILIGREE_LEAF =
  'M34 42C46 26 62 20 78 22 66 34 50 41 34 42Z'
  + 'M34 48c12 14 26 21 42 20-12-11-26-19-42-20Z';

export function filigree(cls = '') {
  return `<g class="orn-fil ${cls}" aria-hidden="true">
    <path class="orn-fil__stem" d="${FILIGREE_STEM}"/>
    <path class="orn-fil__leaf" d="${FILIGREE_LEAF}"/>
    <circle class="orn-fil__berry" cx="127" cy="42" r="2.2"/>
    <circle class="orn-fil__berry" cx="118" cy="57" r="1.9"/>
  </g>`;
}

/** Bat silhouette, wings spread, inside a 100x40 box. */
export const BAT_PATH =
  'M50 9c-2.4 0-4.2 1.8-5.2 4.2C41.4 8.6 35.6 5.6 29 5.6c-4.2 0-8 1.2-11.2 3.4 2.8-.6 5.4.2 7 2.2'
  + '-5.4 1.2-9.8 5-11.8 10.2 3.6-3 7.8-4 12-2.4-3.2 2.8-5 7-4.4 11.4 2.8-5 8-7.6 13.6-6.8'
  + '3.6.6 6.4 2.8 8.2 6 1.8-3.4 4.6-5.4 7.6-5.4s5.8 2 7.6 5.4c1.8-3.2 4.6-5.4 8.2-6'
  + '5.6-.8 10.8 1.8 13.6 6.8.6-4.4-1.2-8.6-4.4-11.4 4.2-1.6 8.4-.6 12 2.4-2-5.2-6.4-9-11.8-10.2'
  + '1.6-2 4.2-2.8 7-2.2C79.2 6.8 75.4 5.6 71.2 5.6c-6.6 0-12.4 3-15.8 7.6C54.4 10.8 52.6 9 50 9Z';

export function bat(cls = '') {
  return `<g class="orn-bat ${cls}" aria-hidden="true"><path d="${BAT_PATH}"/></g>`;
}

/** Corner cobweb: radial spokes + sagging catenary threads. */
export function cobweb(cls = '', rings = 5, spokes = 7) {
  const R = 200;
  let d = '';
  for (let i = 0; i < spokes; i++) {
    const a = (i / (spokes - 1)) * (Math.PI / 2);
    d += `M0 0L${(Math.cos(a) * R).toFixed(1)} ${(Math.sin(a) * R).toFixed(1)}`;
  }
  let arcs = '';
  for (let r = 1; r <= rings; r++) {
    const rad = (r / rings) * R * 0.94;
    let p = '';
    for (let i = 0; i < spokes - 1; i++) {
      const a0 = (i / (spokes - 1)) * (Math.PI / 2);
      const a1 = ((i + 1) / (spokes - 1)) * (Math.PI / 2);
      const am = (a0 + a1) / 2;
      const sag = rad * 0.82;
      const x0 = Math.cos(a0) * rad, y0 = Math.sin(a0) * rad;
      const x1 = Math.cos(a1) * rad, y1 = Math.sin(a1) * rad;
      const xm = Math.cos(am) * sag, ym = Math.sin(am) * sag;
      p += `${i === 0 ? `M${x0.toFixed(1)} ${y0.toFixed(1)}` : ''}Q${xm.toFixed(1)} ${ym.toFixed(1)} ${x1.toFixed(1)} ${y1.toFixed(1)}`;
    }
    arcs += `<path d="${p}"/>`;
  }
  return `<svg class="orn-web ${cls}" viewBox="0 0 200 200" aria-hidden="true">
    <g class="orn-web__spokes"><path d="${d}"/></g>
    <g class="orn-web__rings">${arcs}</g>
  </svg>`;
}

/** Brass candlestick with a live flame. Flame animation is CSS. */
export function candle(cls = '') {
  return `<div class="orn-candle ${cls}" aria-hidden="true">
    <div class="orn-candle__halo"></div>
    <div class="orn-candle__flame"><i></i><b></b></div>
    <svg class="orn-candle__body" viewBox="0 0 60 190">
      <path class="wax" d="M21 40h18c1.6 0 3 1.3 3 3v104H18V43c0-1.7 1.3-3 3-3Z"/>
      <path class="drip" d="M20 62c3 8 1 15 3 22s-1 12 1 18V70Zm20 6c-3 9-1 14-3 21s1 11-1 17V74Z"/>
      <path class="brass" d="M12 147h36l4 9H8Zm7 9h22l-3 16H22Zm-2 16h26c5 0 9 3 9 7H8c0-4 4-7 9-7Z"/>
      <path class="brass2" d="M4 179h52c2 0 3 1.4 3 3v5c0 1.7-1.3 3-3 3H4c-1.7 0-3-1.3-3-3v-5c0-1.6 1.3-3 3-3Z"/>
      <path class="wick" d="M29 34h2v8h-2Z"/>
    </svg>
  </div>`;
}

// ── the logo ────────────────────────────────────────────────────────────────
/**
 * MIDNIGHT MENAGERIE, matching UI/selectCompanion.png: an ornate serif wordmark in a
 * purple/silver gradient on a dark oval cartouche with filigree scrollwork, bats and
 * cobwebs. Text is real DOM so it stays crisp and selectable by a11y tooling; the
 * cartouche and ornaments are SVG.
 *
 *  size    'hero' | 'md' | 'sm'
 *  plaque  optional sub-banner text ('MENAGERIE COMPANIONS')
 */
export function logoLockup({ size = 'hero', plaque = null, id = 'mm-logo' } = {}) {
  const uid = `${id}-${Math.random().toString(36).slice(2, 7)}`;
  const node = el('div', `mm-logo mm-logo--${size}`);
  node.setAttribute('role', 'img');
  node.setAttribute('aria-label', 'Midnight Menagerie');

  node.appendChild(svg(`
  <svg class="mm-logo__plate" viewBox="0 0 1400 360" aria-hidden="true">
    <defs>
      <radialGradient id="${uid}-oval" cx="50%" cy="40%" r="68%">
        <stop offset="0%"  class="s-oval-in"/>
        <stop offset="56%" class="s-oval-mid"/>
        <stop offset="100%" class="s-oval-out"/>
      </radialGradient>
      <linearGradient id="${uid}-rim" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%"   class="s-rim-hi"/>
        <stop offset="20%"  class="s-rim-lo"/>
        <stop offset="52%"  class="s-rim-hi"/>
        <stop offset="84%"  class="s-rim-lo"/>
        <stop offset="100%" class="s-rim-hi"/>
      </linearGradient>
      <filter id="${uid}-soft" x="-40%" y="-40%" width="180%" height="180%">
        <feGaussianBlur stdDeviation="22"/>
      </filter>
    </defs>

    <!-- the halo the cartouche sits in -->
    <ellipse class="mm-logo__halo" cx="700" cy="178" rx="640" ry="176" filter="url(#${uid}-soft)"/>

    <!-- outer scrollwork: arms off each tip, flourishes into the four corners.
         Drawn behind the oval, but placed so the visible mass sits outside it. -->
    <g class="mm-logo__vines">
      <g transform="translate(172,178) scale(-1.06,1.06) translate(0,-45)">${filigree()}</g>
      <g transform="translate(1228,178) scale(1.06,1.06) translate(0,-45)">${filigree()}</g>
      <g transform="translate(250,74)  rotate(-152) scale(.72) translate(0,-45)">${filigree()}</g>
      <g transform="translate(1150,74) rotate(-28)  scale(.72) translate(0,-45)">${filigree()}</g>
      <g transform="translate(250,282) rotate(152)  scale(.72) translate(0,-45)">${filigree()}</g>
      <g transform="translate(1150,282) rotate(28)  scale(.72) translate(0,-45)">${filigree()}</g>
    </g>

    <!-- the cartouche -->
    <ellipse class="mm-logo__oval" cx="700" cy="178" rx="562" ry="166" fill="url(#${uid}-oval)"/>
    <ellipse class="mm-logo__ring mm-logo__ring--out"  cx="700" cy="178" rx="562" ry="166" stroke="url(#${uid}-rim)"/>
    <ellipse class="mm-logo__ring mm-logo__ring--in"   cx="700" cy="178" rx="544" ry="150"/>
    <ellipse class="mm-logo__ring mm-logo__ring--hair" cx="700" cy="178" rx="534" ry="141"/>

    <!-- star dust inside the cartouche -->
    <g class="mm-logo__stars">
      <circle cx="266" cy="140" r="2.3"/><circle cx="318" cy="228" r="1.6"/>
      <circle cx="430" cy="76"  r="1.8"/><circle cx="960" cy="66"  r="2.0"/>
      <circle cx="1096" cy="212" r="1.7"/><circle cx="1132" cy="128" r="2.3"/>
      <circle cx="700" cy="46"  r="1.6"/><circle cx="812" cy="300" r="1.9"/>
      <circle cx="520" cy="300" r="1.5"/><circle cx="1010" cy="286" r="1.7"/>
      <circle cx="212" cy="178" r="1.8"/><circle cx="1188" cy="180" r="1.6"/>
      <circle cx="596" cy="52"  r="1.4"/><circle cx="380" cy="272" r="1.4"/>
    </g>

    <!-- bats flanking the wordmark, as in the source plate -->
    <g class="mm-logo__bats">
      <g transform="translate(196,148) scale(.92)">${bat()}</g>
      <g transform="translate(1116,142) scale(.80)">${bat()}</g>
      <g transform="translate(470,288) scale(.44)">${bat()}</g>
      <g transform="translate(860,292) scale(.36)">${bat()}</g>
    </g>
  </svg>`));

  const text = el('div', 'mm-logo__text');
  text.appendChild(el('span', 'mm-logo__top', 'Midnight'));
  text.appendChild(el('span', 'mm-logo__main', 'Menagerie'));
  node.appendChild(text);

  if (plaque) {
    node.appendChild(svg(`<div class="mm-logo__plaque"><span>&#9733;</span>${plaque}<span>&#9733;</span></div>`));
  }
  return node;
}

// ── the eight Kids ──────────────────────────────────────────────────────────
/**
 * Authored paintings, prepared by `python tools/prep_kid_art.py` and committed
 * (no build step, CONTRACTS #1). Two crops of the same painting per Kid:
 *
 *   portrait  assets/kids/<slug>.jpg        720x960, 3:4.  The whole figure in
 *             their own lamplit corner of the house. The dossier hero and any
 *             other slot big enough to be looked at rather than glanced at.
 *   thumb     assets/kids/<slug>-thumb.jpg  192x192, 1:1.  Head and shoulders,
 *             framed the same way for all eight so a row of them reads as a
 *             roster and not as eight unrelated crops. Tiles and rosters.
 *
 * Before this they were generated in `ui/petart.js` — one body silhouette
 * recoloured per Kid, no faces — and a reviewer named it next to the painted
 * Companions. That generator is deleted, not disabled: two systems for one
 * picture is how a screen ends up showing the wrong one.
 *
 * The pets are still generated, and should stay that way. There is no authored
 * pet art, and a snapshot taken by a frightened child is a thing a generator
 * can genuinely nail; a child's face is not.
 */
export const KID_PORTRAIT_W = 720, KID_PORTRAIT_H = 960;
export const KID_THUMB_PX = 192;

/** `variant`: 'portrait' (3:4 painting) | 'thumb' (192px square head). */
export function kidSrc(slug, variant = 'portrait') {
  const s = String(slug || '');
  return variant === 'thumb' ? `${ASSETS}kids/${s}-thumb.jpg` : `${ASSETS}kids/${s}.jpg`;
}

/**
 * An <img> for one Kid, class `kidpf` so the scene stylesheets that already
 * size these boxes keep working. Intrinsic width/height are on the element
 * before the src is, so the box is the right shape on the first frame and
 * nothing reflows when the file lands.
 */
export function kidImg(slug, { alt, className = 'kidpf', variant = 'portrait' } = {}) {
  const k = KID_BY_SLUG[slug];
  const thumb = variant === 'thumb';
  const img = document.createElement('img');
  img.className = className + (thumb ? ' kidpf--thumb' : '');
  img.decoding = 'async';
  img.draggable = false;
  img.width = thumb ? KID_THUMB_PX : KID_PORTRAIT_W;
  img.height = thumb ? KID_THUMB_PX : KID_PORTRAIT_H;
  img.alt = alt ?? (k ? `${k.name}, looking for ${k.pet}` : 'One of the kids');
  img.src = kidSrc(slug, variant);
  /* A missing thumbnail falls back to the full painting, never to a broken
     image: the crop is then wrong, but the right child is still on screen. */
  if (thumb) {
    img.addEventListener('error', () => { img.src = kidSrc(slug, 'portrait'); }, { once: true });
  }
  return img;
}

/**
 * A Kid portrait, sized so the box it lands in never reflows.
 *
 * Signature kept from the generated version every caller already uses — they
 * pass `{ ...kid, petKind }` and a `{ w, h }`. `variant` is the one addition:
 * pass 'thumb' for a tile or a roster row, leave it for a hero slot.
 */
export function kidPortrait(kid, { w = 260, h = 300, variant = 'portrait' } = {}) {
  const img = kidImg(kid?.slug, { variant });
  /* `w`/`h` become a MAX, not a fixed size, and they are set as data attributes
     rather than inline styles. Inline width/height beat the stylesheet, and
     every one of the boxes these land in already sizes them in CSS — the
     select dossier stretches its portrait to the full height of the panel and
     an inline `height:auto` silently vetoed that. */
  img.style.maxWidth = '100%';
  if (w) img.dataset.w = String(w);
  if (h) img.dataset.h = String(h);
  return img;
}

/**
 * The photograph of one missing pet, as an <img class="petpic">.
 * `any` accepts a kid slug, a pet slug, or a pet name.
 */
export function petPortrait(any, { alt } = {}) {
  return petImg(any, { alt });
}

/**
 * DEPRECATED — the flat species glyph. The MISSING poster used one fixed cat
 * path for every pet including Samir's guinea pig, which is precisely the thing
 * that round was sent to fix. Kept only so nothing outside `scenes/{title,
 * select,clubhouse,gameover}` breaks at import time; every caller in those four
 * now uses `petPortrait`. It returns the cat path and it is meant to be unused.
 */
export function petGlyph() {
  return 'M5 13 3.5 3.5 11 7.5h10l7.5-4L27 13c1.8 2 2.8 4.6 2.8 7.2 0 5.6-5.2 9.3-13.8 9.3'
    + 'S2.2 25.8 2.2 20.2C2.2 17.6 3.2 15 5 13Z';
}

// ── keyboard roving focus ───────────────────────────────────────────────────
/**
 * Grid/list arrow-key navigation with a visible focus ring. Returns a disposer.
 * `cols` 0 = linear list (up/down only).
 */
export function rovingFocus(container, selector, { cols = 0, wrap = true, onActivate } = {}) {
  const items = () => [...container.querySelectorAll(selector)].filter((n) => !n.hidden && !n.disabled);
  const onKey = (e) => {
    const list = items();
    if (!list.length) return;
    const i = list.indexOf(document.activeElement);
    let n = -1;
    const k = e.key;
    if (k === 'ArrowRight' || (cols === 0 && k === 'ArrowDown')) n = i + 1;
    else if (k === 'ArrowLeft' || (cols === 0 && k === 'ArrowUp')) n = i - 1;
    else if (cols > 0 && k === 'ArrowDown') n = i + cols;
    else if (cols > 0 && k === 'ArrowUp') n = i - cols;
    else if (k === 'Home') n = 0;
    else if (k === 'End') n = list.length - 1;
    else if ((k === 'Enter' || k === ' ') && i >= 0 && onActivate) { e.preventDefault(); onActivate(list[i], i); return; }
    else return;
    if (i < 0) n = 0;
    if (n < 0) n = wrap ? list.length - 1 : 0;
    if (n >= list.length) n = wrap ? 0 : list.length - 1;
    e.preventDefault();
    list[n]?.focus();
  };
  container.addEventListener('keydown', onKey);
  return () => container.removeEventListener('keydown', onKey);
}

/** Format a seed as the game shows it: XXXX-XXXX. */
export function formatSeed(seed) {
  const s = Math.abs(Number(seed) | 0).toString(36).toUpperCase().padStart(8, '0').slice(-8);
  return `${s.slice(0, 4)}-${s.slice(4)}`;
}

/**
 * Read a seed back out of the shown form. Round-trips `formatSeed` exactly —
 * a 31-bit seed is at most six base-36 digits, so the eight-digit window never
 * truncates one. Returns null for anything that is not a seed.
 */
export function parseSeed(text) {
  const s = String(text ?? '').replace(/[^0-9a-z]/gi, '').toUpperCase();
  if (!s || s.length > 8) return null;
  const n = parseInt(s, 36);
  // Out of range is REJECTED, not wrapped. Folding a too-large value into range
  // would answer "ZZZZ-1234" with a different seed than the one just typed,
  // which is the one thing a seed field must never do.
  if (!Number.isFinite(n) || n < 0 || n > 0x7fffffff) return null;
  return n >>> 0;
}
