"""Which enemies still have no painting, and the exact filename each one wants.

    python tools/enemy_art_checklist.py            # writes docs/art/enemy-stills-checklist.md
    python tools/enemy_art_checklist.py --check    # exit 1 if a suggested name would not resolve

Josh paints enemy stills into `animations/sprites/enemies/`, and so far has
named them by display name in camelCase (`The Bedframe Beast` ->
`bedframeBeast.png`). `tools/prep_sprites.py` keys a still by EnemyDef id, and a
name that does not convert to the id — `wardrobe`, `prim`, `sporepuff` — builds
under a key nothing asks for, which reads on the board exactly like a painting
nobody delivered. Measured over the whole registry, display names would have
put 44 stills under the wrong key and given three pairs of enemies one name.

So every suggested filename is the enemy's ID in camelCase — for most enemies
the same as its name without "The" — generated from the registry, never kept by
hand (CONTRACTS trap 60), and run through `prep_sprites.enemy_id_of_still`, the
build's own resolver, before it is printed. `--check` fails if one would not
land on its enemy.

Needs node (the registry is the game's own JS).
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import prep_sprites as P  # noqa: E402

OUT = os.path.join(ROOT, "docs", "art", "enemy-stills-checklist.md")

DUMP = """
Promise.all([import('./game/src/data/enemies/index.js'), import('./game/src/data/schema.js')]).then(([m, s]) => {
  const defs = Object.values(m.ENEMIES).map(d => ({
    id: d.id, name: d.name, region: d.region, tier: d.tier, role: d.role,
    summonOnly: !!d.summonOnly, partOf: d.partOf || null,
  }));
  console.log(JSON.stringify({ order: s.REGION_ORDER, defs }));
});
"""


def node():
    for c in (shutil.which("node"), r"C:\\Program Files\\nodejs\\node.exe"):
        if c and os.path.exists(c):
            return c
    sys.exit("node not found")


def suggested(enemy_id):
    """`bedframe-beast` -> `bedframeBeast.png`: the id, camelCased.

    NOT the display name, though that is how most of the art has arrived and
    for most enemies the two agree. Where they do not, the name is a loose key:
    44 of the 275 would have built under the wrong id (`A Small Grey Dog` is
    `ward-pup`, `Crown` is `hedge-crown`) and three pairs share a name outright
    (two Spark Pumpkins). The id is unique and converts back mechanically."""
    parts = [p for p in enemy_id.split("-") if p]
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:]) + ".png"


def kind(d):
    if d["tier"] == "boss" and d["role"] == "boss":
        return "Boss", "1024"
    if d["role"] == "bossPart" or d["partOf"]:
        return "part of a boss or Big Scare", "512"
    if d["tier"] == "elite":
        return "Big Scare" if not d["summonOnly"] else "Big Scare summon", "512"
    return ("summon" if d["summonOnly"] else "Scuffle"), "256"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    raw = subprocess.run([node(), "-e", DUMP], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    reg = json.loads(raw)
    manifest = json.load(open(os.path.join(ROOT, "game", "assets", "sprites", "index.json")))
    painted = set((manifest.get("enemies") or {}).keys())
    by_region = {}
    for d in reg["defs"]:
        by_region.setdefault(d["region"], []).append(d)

    wrong, clashes, seen = [], [], {}
    for d in reg["defs"]:
        fn = suggested(d["id"])
        got = P.enemy_id_of_still(fn) if fn else None
        d["file"] = fn
        if got != d["id"]:
            wrong.append((d["id"], d["name"], fn, got))
        if fn in seen and seen[fn] != d["id"]:
            clashes.append((fn, seen[fn], d["id"]))
        seen[fn] = d["id"]

    if a.check:
        for id_, name, fn, got in wrong:
            print("  %-26s %-34s %-30s resolves to %s" % (id_, name, fn, got))
        for fn, x, y in clashes:
            print("  %s is the suggested name of both %s and %s" % (fn, x, y))
        print("RESULT: %d enemies, %d painted, %d names need an alias, %d clashes"
              % (len(reg["defs"]), len(painted), len(wrong), len(clashes)))
        return 1 if (wrong or clashes) else 0

    total = len(reg["defs"])
    lines = [
        "# Enemy stills — what is painted, and what each missing one should be called",
        "",
        "Generated by `python tools/enemy_art_checklist.py` from the enemy registry and",
        "the built sprite manifest. Do not edit by hand; re-run it.",
        "",
        "**%d of %d enemies are painted.**" % (len(painted & {d['id'] for d in reg['defs']}), total),
        "",
        "Drop a painting in `animations/sprites/enemies/` under the filename in its",
        "row, then `python tools/prep_sprites.py --enemies`. Every filename below is",
        "checked against the build's own resolver, so it lands on its enemy.",
        "",
        "Sizes are what the art so far was delivered at: 256 for Scuffle creatures,",
        "512 for Big Scares and every part or summon of one, 1024 for bosses. A part",
        "is drawn beside the body it belongs to — the Hydra's Heads stand next to the",
        "Hydra — so paint it on its own, not as a crop of the body.",
        "",
    ]
    unknown_regions = [r for r in by_region if r not in reg["order"]]
    for region in list(reg["order"]) + unknown_regions:
        defs = by_region.get(region) or []
        if not defs:
            continue
        missing = [d for d in defs if d["id"] not in painted]
        lines.append("## %s — %d of %d painted" % (region, len(defs) - len(missing), len(defs)))
        lines.append("")
        if not missing:
            lines.append("Every enemy in this wing is painted.")
            lines.append("")
            continue
        lines.append("| file | enemy | what it is | size |")
        lines.append("|---|---|---|---|")
        order = {"Boss": 0, "Big Scare": 1, "Scuffle": 2}
        for d in sorted(missing, key=lambda d: (order.get(kind(d)[0], 3), d["name"])):
            k, size = kind(d)
            lines.append("| `%s` | %s | %s | %s |" % (d["file"], d["name"], k, size))
        lines.append("")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("wrote %s: %d enemies, %d painted, %d names need an alias, %d clashes"
          % (os.path.relpath(OUT, ROOT), total, len(painted), len(wrong), len(clashes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
